spring:
  data:
    cassandra:
      keyspace-name: main
      username: MhNZnxHGWxGvciOgKqPAYxoh
      password: nhK9EioYAPR1IRGdzxhpCFkSEL8n32Jy3HTv+3n++TaZS9O_-l0fO-ox9cf5Ckwr0AwF8HZI-QWTyxzYDzmZxliIweUZs4dyadxE0p,aBURmeCZ5F+5+fD7RjUY+KDYj
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: c100af9a-b941-4aa3-b999-7234863feffe-1
    region: asia-south1
    keyspace: main
    application.token: AstraCS:MhNZnxHGWxGvciOgKqPAYxoh:cff955cfec2fce5829c075ef4cf637c5d0d08738587306854c97f21c37ac55a3


